ui_print "- Disable Skia Tracing"
ui_print ""
ui_print "- Disabling Trace for skiagl rendering to avoid overhead."
ui_print ""
ui_print "- Better to see Github or Telegram Channel to know how module works!"
ui_print ""
ui_print "- @kntdreborn - Telegram Channel"
ui_print ""
ui_print "- github.com/Kntd-Reborn - Github"
ui_print ""
ui_print ""